### ISSUE TITLE
Initialize docusaurus

### ISSUE THREAD

**Issue by alvarobernal2412** [DevPathGame/.github#4]
Definition of `Done`
- [x] A repository containing the project's docusaurus has been created.
- [x] The initial styles of the docusaurus have been adapted.
- [x] It has been published on GitHub Pages and a redeployment workflow has been added.

**Comment by alvarobernal2412** [comment]
This PR has been done the docs [main branch](https://github.com/DevPathGame/knowledge-base), from now on issues will be associated with PRs. 

@JaviGarc1a should verify that I comply with the DoD and close this issue.

**Comment by JaviGarc1a** [comment]
This issue will be closed as 'Done' due to the initialize correctly.
